### ISSUE TITLE
Please fix code repo link

### ISSUE THREAD

**Issue by pcav** [abocianowski/ObliczWysokosc#2]
Currently:
https://github.com/abocianowski/ObliczWysokoscchangelog:version=0.1%20(2019-10-31):*%20plugin%20create
Thanks

**Comment by abocianowski** [comment]
Hi, it's funny but in metadata file I have:
https://github.com/abocianowski/ObliczWysokosc

look at this:
![image](https://user-images.githubusercontent.com/50774139/67969918-6cfe7a00-fc0a-11e9-9614-1456b4a967fa.png)
When upload plugin to qgis plugins website it s changes automatically.
What Can I do with that ?

**Comment by pcav** [comment]
I think you can change it from the web interface
thanks

**Comment by abocianowski** [comment]
You have right, code link repo was changed:
![image](https://user-images.githubusercontent.com/50774139/67970532-6d4b4500-fc0b-11e9-86ca-5d0fa8baa133.png)
