### ISSUE TITLE
Interface translatable

### ISSUE THREAD

**Issue by pcav** [abocianowski/ObliczWysokosc#3]
Is the interface transaltable? Is the default in English?
Thanks.

**Comment by abocianowski** [comment]
No, interface is only in Polish language. This plug-in is mainly directed to Polish Qgis users, which is indicated by the header of the plug-in description. By the way, there are plugins in the repository that are not translated and I provide metadata about use only in Poland. For example: https://plugins.qgis.org/plugins/nmt_gugik/

**Comment by pcav** [comment]
Thanks for letting me know. I opened another ticket on the other plugin - if you find other, just let me know.
What has this plugin of specifically Polish? From the description it seems of general use.
Thanks.

**Comment by abocianowski** [comment]
Plugin uses the digital terrain model data provided by the main surveying office in Poland. The service coverage area is available only within the administrative borders of Poland. In the short description of the plugin I have included information about availability only for Polish users. Please look:
![image](https://user-images.githubusercontent.com/50774139/67971105-72f55a80-fc0c-11e9-8365-64e9e9026366.png)

As you suggested, I added additional descriptions. I hope that's enough. Thanks
![image](https://user-images.githubusercontent.com/50774139/67971248-bc45aa00-fc0c-11e9-88a0-467ba78198c3.png)

**Comment by pcav** [comment]
Fine, thanks.
