### ISSUE TITLE
Pusta lista warstw

### ISSUE THREAD

**Issue by adrase** [abocianowski/ObliczWysokosc#4]
Hej. Totalnie nie działa u mnie liczenie spadku terenu. Na liście warstw do wyboru nic nie mam. Czy warstwa liniowa, dla której liczone są spadki, musi być w jakimś konkretnym formacie/typie geometrii? Używam QGIS 3.10 na Ubuntu 18.04

**Comment by abocianowski** [comment]
Cześć, dziękuję za zgłoszenie. Błąd faktycznie występował w systemie Ubuntu i został naprawiony w wersji 0.6, która niebawem będzie oficjalnie dostępna - https://plugins.qgis.org/plugins/ObliczWysokosc/version/0.6/
Pozdrawiam.
